# Generated by Django 4.2.14 on 2024-07-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='restorent',
            name='floors',
        ),
        migrations.AddField(
            model_name='floor',
            name='floors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restorent.restorent'),
        ),
        migrations.AddField(
            model_name='table',
            name='tables',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restorent.floor'),
        ),
    ]
