# Generated by Django 4.2.14 on 2024-07-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0002_remove_floor_tables_remove_restorent_floors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='floors',
            new_name='restorent_id',
        ),
        migrations.RemoveField(
            model_name='table',
            name='tables',
        ),
        migrations.AddField(
            model_name='table',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restorent.floor'),
        ),
    ]
