# Generated by Django 4.2.14 on 2024-07-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0003_rename_floors_floor_restorent_id_remove_table_tables_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='restorent_id',
            new_name='restorent',
        ),
    ]
