# Generated by Django 4.2.14 on 2024-07-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
    ]
