# Generated by Django 4.2.14 on 2024-07-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0006_remove_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('food_type', models.CharField(max_length=20)),
                ('catogary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorent.restorent')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restorent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorent.restorent')),
            ],
        ),
    ]
