# Generated by Django 4.2.14 on 2024-07-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0007_fooditem_foodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(default='default_food_img.png', upload_to='food_images'),
        ),
    ]
