# Generated by Django 4.2.14 on 2024-07-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0008_fooditem_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='catogary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorent.foodcategory'),
        ),
    ]
