# Generated by Django 4.2.14 on 2024-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0009_alter_fooditem_catogary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
