# Generated by Django 4.2.14 on 2024-07-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0010_fooditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg'), ('egg', 'Egg')], max_length=20),
        ),
    ]
