# Generated by Django 4.2.14 on 2024-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0011_alter_fooditem_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], max_length=20),
        ),
    ]
