# Generated by Django 4.2.14 on 2024-07-18 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0012_alter_fooditem_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax_perscentage', models.FloatField()),
                ('restorent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorent.restorent')),
            ],
        ),
    ]
