# Generated by Django 4.2.14 on 2024-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='restorent.fooditem'),
        ),
    ]
