# Generated by Django 4.2.14 on 2024-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0016_remove_order_items_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
