# Generated by Django 4.2.14 on 2024-07-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0017_alter_order_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order_panding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='payment_panding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='vacent_status',
            field=models.BooleanField(default=False),
        ),
    ]
