# Generated by Django 4.2.14 on 2024-07-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0018_table_order_panding_table_payment_panding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField()),
                ('timing', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=30)),
                ('adjustment', models.FloatField()),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restorent.order')),
            ],
        ),
    ]
