# Generated by Django 4.2.14 on 2024-07-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0019_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
    ]
