# Generated by Django 4.2.14 on 2024-07-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0020_rename_order_id_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timing',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
