# Generated by Django 4.2.14 on 2024-07-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0021_alter_order_start_time_alter_payment_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('UPI', 'UPI'), ('CARD', 'CARD')], max_length=30),
        ),
    ]
