# Generated by Django 4.2.14 on 2024-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0022_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
