# Generated by Django 4.2.14 on 2024-08-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0023_payment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorent',
            name='upi_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
