# Generated by Django 4.2.14 on 2024-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0024_restorent_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorent',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
