# Generated by Django 4.2.14 on 2024-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0025_alter_restorent_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
