# Generated by Django 4.2.14 on 2024-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0026_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='adjustment',
        ),
        migrations.AddField(
            model_name='order',
            name='adjustment',
            field=models.FloatField(default=0),
        ),
    ]
