# Generated by Django 4.2.14 on 2024-08-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0027_remove_payment_adjustment_order_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restorent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restorent.restorent'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
