# Generated by Django 4.2.14 on 2024-08-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0028_order_restorent_table_table_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_type',
        ),
        migrations.AddField(
            model_name='order',
            name='food_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
