# Generated by Django 4.2.14 on 2024-08-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0029_remove_table_table_type_order_food_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='normal_table',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
