# Generated by Django 4.2.14 on 2024-08-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0030_order_address_order_name_order_normal_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorent',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
