# Generated by Django 4.2.14 on 2024-09-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0031_restorent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorent',
            name='notification_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
