# Generated by Django 4.2.14 on 2024-09-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0033_alter_restorent_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorent',
            name='restorent_type',
            field=models.CharField(choices=[('restorent', 'Restorent'), ('theatre', 'Theatre')], default='restorent', max_length=20),
        ),
    ]
