# Generated by Django 4.2.14 on 2024-09-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restorent', '0034_restorent_restorent_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restorent',
            old_name='restorent_type',
            new_name='type',
        ),
    ]
